# Server
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://thinturedb.c3oqsa2ui3r2.ap-south-1.rds.amazonaws.com:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=Thinture24
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# Slack
slack.webhook.url=https://hooks.slack.com/services/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

# GitHub
github.webhook.secret=your_github_webhook_secret